### ISSUE TITLE
precompile failure

### ISSUE THREAD

**Issue by davidcoble** [trwnh/mastomods#4]
I followed the instructions in the readme.
<pre>

/home/mastodon/live$ grep linernotes config/locales/en.yml 
    linernotes_dark: Liner Notes (Dark)

/home/mastodon/live$ cat config/themes.yml 
default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
linernotes_dark: styles/linernotes_dark.scss

/home/mastodon/live$ ls -R app/javascript/styles/
app/javascript/styles/:
application.scss  fonts                 mailer.scss     mastodon-light.scss
contrast          linernotes_dark       mastodon        mfc
contrast.scss     linernotes_dark.scss  mastodon-light  mods

app/javascript/styles/contrast:
diff.scss  variables.scss

app/javascript/styles/fonts:
montserrat.scss  roboto-mono.scss  roboto.scss

app/javascript/styles/linernotes_dark:
overrides.scss  palette.scss

app/javascript/styles/mastodon:
_mixins.scss        boost.scss           footer.scss        reset.scss
about.scss          compact_header.scss  forms.scss         rtl.scss
accessibility.scss  components.scss      introduction.scss  stream_entries.scss
accounts.scss       containers.scss      lists.scss         tables.scss
admin.scss          dashboard.scss       modal.scss         variables.scss
basics.scss         emoji_picker.scss    polls.scss         widgets.scss

app/javascript/styles/mastodon-light:
diff.scss  variables.scss

app/javascript/styles/mfc:
0-palette.css     2-background.css  4-fixes.css     6-actions.css      variables.scss
1-foreground.css  3-highlights.css  5-material.css  mastodonFlat.scss

app/javascript/styles/mods:
deprecated                         display_transparentmedia.css
display_breakname.css              layout_1600px.css
display_browserfont.css            layout_elefriend.css
display_circleavatar.css           layout_gettingstartedheight.css
display_collapsedinteractions.css  layout_hidedisabled.css
display_emojizoom.css              layout_hidefiltered.css
display_fadedinteractions.css      layout_mobile_bottombar.css
display_fullmedia.css              layout_singlecolumn.css
display_fullname.css               layout_widercolumns.css
display_hidereplycounts.css        test_colorizedlogo.css
display_starstohearts.css

app/javascript/styles/mods/deprecated:
display_bettersearch.css

/home/mastodon/live$ RAILS_ENV=production bundle exec rails assets:precompile --verbose
yarn install v1.19.0
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 3.65s.
Compiling…
^C#<Thread:0x0000007f7e78b4c0@/home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/open3.rb:287 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/open3.rb:287:in `block (2 levels) in capture3'
/home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/open3.rb:287:in `read': stream closed in another thread (IOError)
#<Thread:0x0000007f7e78a818@/home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/open3.rb:288 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/open3.rb:288:in `block (2 levels) in capture3'
/home/mastodon/.rbenv/versions/2.6.1/lib/ruby/2.6.0/open3.rb:288:in `read': stream closed in another thread (IOError)
rails aborted!
Interrupt: 
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/webpacker/compiler.rb:61:in `run_webpack'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/webpacker/compiler.rb:21:in `compile'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/webpacker/commands.rb:18:in `compile'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/webpacker.rb:27:in `compile'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/tasks/webpacker/compile.rake:31:in `block (4 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/tasks/webpacker/compile.rake:6:in `ensure_log_goes_to_stdout'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/tasks/webpacker/compile.rake:30:in `block (3 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/webpacker.rb:20:in `with_node_env'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/tasks/webpacker/compile.rake:29:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/webpacker-4.0.7/lib/tasks/webpacker/compile.rake:22:in `block in enhance_assets_precompile'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)

**Comment by trwnh** [comment]
ah hm. it may be that i deprecated the "better search" mod but forgot to change the imports in scss. ~~apparently not? need to look into this more~~ apparently yes, and one other thing

**Comment by trwnh** [comment]
ok, should work now! had some imports that no longer existed or were renamed.

**Comment by trwnh** [comment]
let me know if it still happens and i'll reopen this and take another stab at it
