### ISSUE TITLE
Status actions modal entirely broken on mobile devices

### ISSUE THREAD

**Issue by umonaca** [trwnh/mastomods#6]
### Screenshot

![image](https://user-images.githubusercontent.com/53662960/86531598-bc2f3580-be90-11ea-80fd-07665cb03fe6.png)

### Steps to reproduce

This bug exists not only on midnight-blue, but also in many other themes, such as Linernotes Dark.

1. Open Firefox/Chrome, switch to mobile view
2. Force refresh the page, click the "..." button next to any status
3. You will see the screenshot

Note that on desktop mode, clicking the "..." button will not trigger status action modal. A normal actions menu will be shown instead.

**Comment by trwnh** [comment]
i think it's actually the touch menu instead of a mobile menu. it's being tracked in #3
