### ISSUE TITLE
Multiple unthemed features

### ISSUE THREAD

**Issue by umonaca** [trwnh/mastomods#8]
Some of features still missing themes:

### List adder

![image](https://user-images.githubusercontent.com/53662960/86928482-9741f900-c102-11ea-88fa-866bd30ba2c3.png)

(You can ignore the subscribe button. It's not in vanilla version of mastodon.)
DId you intentionally leave the color unchanged? Well I think it's fine.

### Log entries

In the admin section.

![image](https://user-images.githubusercontent.com/53662960/86928761-fd2e8080-c102-11ea-97b8-021531883d3c.png)

### Dashboard counters

In the admin section.

![image](https://user-images.githubusercontent.com/53662960/86928951-3ff05880-c103-11ea-8b66-a538aa384003.png)

### Accouncement

In the admin section.

![image](https://user-images.githubusercontent.com/53662960/86929010-572f4600-c103-11ea-9f12-decd492badd6.png)

**Comment by trwnh** [comment]
i'll check out the lists modal, but i'm not an admin on any instances so i tend to miss the other stuff

**Comment by umonaca** [comment]
You can run a local dev version of Mastodon. It includes all the admin features. It won't take more than 20 minutes to install.

I could propose a PR later but I'm not sure how to apply correct color and theme to the Dashboard part. Other unthemed admin features are pretty much straightforward.
