### ISSUE TITLE
Upstream update on boost icon

### ISSUE THREAD

**Issue by umonaca** [trwnh/mastomods#9]
Upstream has changed their boost icon. If you are planning to match upstream updates the following information might be helpful:

1. Boost icon for private toots that cannot be boosted
[tootsuite#14373](https://github.com/tootsuite/mastodon/pull/14373)
2. Boost icon for private toots that can be boosted (which means you are the author and you can boost to your audiences)
[tootsuite#14380](https://github.com/tootsuite/mastodon/pull/14380)
[tootsuite#14386](https://github.com/tootsuite/mastodon/pull/14386)

**Comment by trwnh** [comment]
probably not -- the existing mfc actions style is already a hack, since it replaces the entire icon with a static version. i'm probably not gonna touch the boost icon ever again unless the animated svg becomes stylable with `svg fill`.

**Comment by trwnh** [comment]
for now i've changed back to option 1 instead of option 2
